---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart iptables
  service:
    name: iptables
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
